<#
.SYNOPSIS
    Inserts a new SSH host block into the entities collection at the specified position.

.DESCRIPTION
    This function takes a collection of SSH config entities and inserts a new HostBlock entity
    at the position specified by the InsertionIndex object. It automatically adds appropriate
    blank line spacing before and after the new block, parses the block text to extract metadata,
    and returns the modified entities collection.

.PARAMETER Entities
    A collection of SSH config entities (typically returned from Get-SshConfigEntities).
    This collection will be modified and returned.

.PARAMETER InsertionIndex
    An insertion index object (returned from Get-SshInsertionIndex) that specifies where 
    to insert the new host block.

.PARAMETER BlockText
    The formatted SSH host block text to insert (typically generated by New-SshHostBlockText).
    Should include the Host line and all configuration options.

.PARAMETER NoBlankLineBefore
    When specified, suppresses the blank line that is normally added before the new host block.

.PARAMETER NoBlankLineAfter
    When specified, suppresses the blank line that is normally added after the new host block.

.NOTES
    Author: Jan Blomberg
    Date: 2025-12-23
    Version: 1.0

.EXAMPLE
    $entities = Get-SshConfigEntities -Path "~/.ssh/config"
    $index = Get-SshInsertionIndex -Entities $entities
    $blockText = New-SshHostBlockText -Patterns 'myserver' -Options @{HostName='10.0.1.50'}
    $entities = Insert-SshHostBlock -Entities $entities -InsertionIndex $index -BlockText $blockText
    Save-SshConfig -Entities $entities -Path "~/.ssh/config"
    
    Complete workflow: parse, insert, and save.

.EXAMPLE
    $entities = Insert-SshHostBlock -Entities $entities -InsertionIndex $index -BlockText $text -NoBlankLineBefore
    
    Inserts without a blank line before the block (useful for very first entry).
#>
function Insert-SshHostBlock {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [System.Collections.Generic.List[object]]$Entities,

        [Parameter(Mandatory)]
        [PSCustomObject]$InsertionIndex,

        [Parameter(Mandatory)]
        [string]$BlockText,

        [switch]$NoBlankLineBefore,
        [switch]$NoBlankLineAfter
    )

    Write-Verbose "Inserting host block at line $($InsertionIndex.InsertAtLine)"
    Write-Verbose "Section: $($InsertionIndex.Section)"

    # Parse the block text to create a proper HostBlock entity
    $lines = $BlockText -split "`r?`n"
    $hostLine = $lines[0]

    # Extract patterns from the Host line
    if ($hostLine -match '^\s*Host\s+(.+)$') {
        $patterns = @($Matches[1] -split '\s+' | Where-Object { $_ })
    } else {
        throw "Invalid host block text: must start with 'Host' directive"
    }

    # Detect if this is a bastion host
    $isBastion = ($patterns | Where-Object { $_ -like 'jump*' }).Count -gt 0

    # Create the new HostBlock entity
    # Note: StartLine and EndLine will be recalculated when saved
    $newHostBlock = [PSCustomObject]@{
        Type      = 'HostBlock'
        StartLine = $InsertionIndex.InsertAtLine
        EndLine   = $InsertionIndex.InsertAtLine + $lines.Count - 1
        RawText   = $BlockText.TrimEnd("`r`n")
        HostLine  = $hostLine.Trim()
        Patterns  = $patterns
        IsBastion = $isBastion
    }

    # Find the insertion point in the entities list
    $insertPosition = 0
    if ($InsertionIndex.InsertAfterEntity) {
        # Find the entity in the list
        for ($i = 0; $i -lt $Entities.Count; $i++) {
            if ($Entities[$i] -eq $InsertionIndex.InsertAfterEntity) {
                $insertPosition = $i + 1
                break
            }
        }
    }

    # Build list of entities to insert (blank lines + host block)
    $toInsert = New-Object 'System.Collections.Generic.List[object]'

    # Add blank line before (unless suppressed or at beginning)
    if (-not $NoBlankLineBefore -and $insertPosition -gt 0) {
        $blankBefore = [PSCustomObject]@{
            Type      = 'BlankBlock'
            StartLine = 0  # Will be recalculated
            EndLine   = 0
            RawText   = ''
        }
        $toInsert.Add($blankBefore)
    }

    # Add the host block
    $toInsert.Add($newHostBlock)

    # Add blank line after (unless suppressed)
    if (-not $NoBlankLineAfter) {
        $blankAfter = [PSCustomObject]@{
            Type      = 'BlankBlock'
            StartLine = 0  # Will be recalculated
            EndLine   = 0
            RawText   = ''
        }
        $toInsert.Add($blankAfter)
    }

    # Insert all entities at the calculated position
    $Entities.InsertRange($insertPosition, $toInsert)

    Write-Verbose "Inserted $($toInsert.Count) entities (including spacing)"
    Write-Verbose "New total entity count: $($Entities.Count)"

    return $Entities
}
